### ISSUE TITLE
add EquateString to cmpopts

### ISSUE THREAD

**Issue by fstanis** [google/go-cmp#134]
I found myself needing this simple function that just compares the string value of two Stringer-compatible objects:

```
cmp.Comparer(func(x, y fmt.Stringer) bool { return x.String() == y.String() })
```

I propose adding this to cmpopts as e.g. `EquateString`.

**Comment by dsnet** [comment]
Thanks for the proposal.

Comparing on the String method is generally considered poor practice since many types do not have documented guarantees of what the `String` method even means. For example, [`regexp.Regexp.String`](https://golang.org/pkg/regexp/#Regexp.String) does specify that the `String` method returns source regexp, while [`reflect.Type.String`](https://godoc.org/reflect#Type.String) warns against comparing on the `String` method. Most types follow the later model where `String` is intended as human debugging aid and not as a mechanism for semantic interpretation.

Also, a helper function like this will likely overly match on too many types since many types have a `String` method, leading to this helper option having a high probability of conflicting with another option.
