### ISSUE TITLE
Get tag struct field inside reporter

### ISSUE THREAD

**Issue by maeglindeveloper** [google/go-cmp#138]
Hi everyone,

I'm actually trying to make a `Diff` between 2 objects. I want to create a custom reporter to get back the `path` of the fields which have been changed from `obj1` to `obj2`, using the "json" tag of the field.

For example, if the calling code of the user has been changed, the path would be something like this : `phone.callingCode` and not `Phone.CallingCode` like the reporter I created is doing right now :s.

This is the structure for my 2 objects

```
type Phone struct {
	CallingCode int `json:"callingCode"`
}
type User struct {
	Name  string `json:"name"`
	Phone Phone  `json:"phone"`
}
```
And here is the code of my current reporter : 
```
type DiffReporter struct {
	path  cmp.Path
	Diffs []string
}

func (r *DiffReporter) PushStep(ps cmp.PathStep) {
	r.path = append(r.path, ps)
}

func (r *DiffReporter) Report(rs cmp.Result) {
	if !rs.Equal() {
		r.Diffs = append(r.Diffs, r.path.String())
	}
}

func (r *DiffReporter) PopStep() {
	r.path = r.path[:len(r.path)-1]
}

func (r *DiffReporter) String() string {
	return strings.Join(r.Diffs, "\n")
}
```
Is there a way to have, in the `Report` or `PushStep` function,  the json tag field rather than the name of the structure field ?

Thanks in advance :)

**Comment by dsnet** [comment]
Given a `cmp.StructField`, you can obtain an `reflect.StructField` by going to the previous `cmp.PathStep`, calling the `Type` method to obtain a `reflect.Type` representing the struct type, and then call the `Field` method.

That said, I'm not sure `cmp` can help you since `cmp.Equal` reports two values to be inequal if they do not have the exact same Go type. According to the Go spec, even if two structs have the exact same field layout, but with different tags, they are still considered different types. Thus, `cmp` won't even descend to the point where it would report two fields being different due to the struct tags.

**Comment by maeglindeveloper** [comment]
Hey @dsnet  ! Thanks for the anwser :) 
I'm going to figure it out with your advice ! 
Thanks again 👍

**Comment by dsnet** [comment]
Glad I could help. Closing as resolved.
