### ISSUE TITLE
comparing different types

### ISSUE THREAD

**Issue by mig4** [google/go-cmp#154]
Hi, just a question about comparing different types as docs don't explicitly say it's not possible, but it's not working for me so far. Example on [playground](https://play.golang.org/p/qpS0IBfN9yI).

So it's a case where two structs have a lot of common fields, but also some specific to each one. I tried using `cmpopts.IgnoreFields` to ignore the differences, but still getting negative results from `cmp.Equal`.

Am I missing something, or is this not possible currently? Should it be possible (would be very handy for me :wink: )?

**Comment by dsnet** [comment]
The top-level values are passed to `Equal` as interface values. In such a situation, the following rule triggers:
> Pointers and interfaces are equal if they are both nil or both non-nil, where they have the same underlying concrete type and recursively calling Equal on the underlying values reports equal.

Since they are not the same type, the equality reports false.

There isn't really an easy way to compare two different struct types with overlapping fields. You probably need to use some transformer to match on the interface type convert *TSpec and *TStatus into a common type that has the relevant fields of both.

**Comment by mig4** [comment]
I suspected that may be the case. Well, I was toying with the idea of extracting the common parts of those structs anyway, I guess I'll just go ahead and do it. Thanks for answering @dsnet!
