### ISSUE TITLE
Compare func pointers

### ISSUE THREAD

**Issue by index0h** [google/go-cmp#162]
Hi. `cmp.Equal` returns `false` for struct fields with same function values.

```go
package main

import (
	"fmt"
	"github.com/google/go-cmp/cmp"
)

func main() {
	callBack := func() string { return "data" }

	type MyStruct struct {
		CallBack func() string
	}

	first := &MyStruct{CallBack: callBack}
	second := &MyStruct{CallBack: callBack}

	if !cmp.Equal(first, second) {
		fmt.Println(cmp.Diff(first, second))
	}
}
```

Result:
```
  &main.MyStruct{
-       CallBack: ⟪0x50f210⟫,
+       CallBack: ⟪0x50f210⟫,
  }

```

My environment:
go: 1.13
go-cmp: 0.3.1

**Comment by dsnet** [comment]
The ability to compare function pointers was considered but rejected because the Go language provides no guarantees about what properties can be depended upon other than checking whether they are nil.

The fact that a `func` type is a "pointer" is actually an implementation detail. In some implementations of the Go language, they can be something else entirely. Since `cmp` tries to be cross-platform, we can't bake that knowledge into the library.

If you really want to compare function pointers, [you can do the following](https://play.golang.org/p/1MKFVzAbsj1):
```go
var equateFuncs = cmp.Comparer(func(x, y func() string) bool {
	px := *(*unsafe.Pointer)(unsafe.Pointer(&x))
	py := *(*unsafe.Pointer)(unsafe.Pointer(&y))
	return px == py
})

if !cmp.Equal(first, second, equateFuncs) {
	fmt.Println(cmp.Diff(first, second))
}
```

**Comment by dsnet** [comment]
I should note that this approach is only reliable on the main Go implementation, and it's behavior is undefined for function closures.
