### ISSUE TITLE
retrieveUnexportedField violates Go 1.14's checkptr validation, fails under -race

### ISSUE THREAD

**Issue by bradfitz** [google/go-cmp#167]
With Go tip (to become Go 1.14) and its new checkptr mode (enabled by default in `-race` mode on anything but Windows for now):

```
=== CONT  TestDiff/EqualMethod/StructE1
panic: runtime error: unsafe pointer arithmetic [recovered]
        panic: runtime error: unsafe pointer arithmetic [recovered]
        panic: runtime error: unsafe pointer arithmetic

goroutine 142 [running]:
testing.tRunner.func1(0xc000238d00)
        /home/bradfitz/go/src/testing/testing.go:881 +0x69f
panic(0x6f3c00, 0xc00000f5e0)
        /home/bradfitz/go/src/runtime/panic.go:679 +0x1b2
github.com/google/go-cmp/cmp_test.TestDiff.func1.1.1(0xc000097eb8)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare_test.go:70 +0xfe
panic(0x6f3c00, 0xc00000f5e0)
        /home/bradfitz/go/src/runtime/panic.go:679 +0x1b2
github.com/google/go-cmp/cmp.retrieveUnexportedField(0x6e33c0, 0xc000128ad8, 0x199, 0x6ad073, 0xd, 0x6b70c3, 0x31, 0x778440, 0x6d34e0, 0x0, ...)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/export_unsafe.go:22 +0x7d
github.com/google/go-cmp/cmp.StructField.Values(0xc0002bd300, 0x8, 0x42c5e0, 0x0, 0x0, 0xc00026f6c0, 0x203000)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/path.go:190 +0x187
github.com/google/go-cmp/cmp.(*valueNode).PushStep(0xc0000a8420, 0x775540, 0xc0002bd300, 0x45bc9a)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/report_value.go:54 +0x5d
github.com/google/go-cmp/cmp.(*defaultReporter).PushStep(0xc00027d680, 0x775540, 0xc0002bd300)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/report.go:24 +0x6e
github.com/google/go-cmp/cmp.(*state).compareAny(0xc0002be900, 0x775540, 0xc0002bd300)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:214 +0x22d
github.com/google/go-cmp/cmp.(*state).compareStruct(0xc0002be900, 0x778440, 0x6e33c0, 0x6e33c0, 0xc000128ad8, 0x199, 0x6e33c0, 0xc000128ae0, 0x199)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:383 +0x548
github.com/google/go-cmp/cmp.(*state).compareAny(0xc0002be900, 0x775480, 0xc000012a00)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:252 +0x1a58
github.com/google/go-cmp/cmp.(*state).comparePtr(0xc0002be900, 0x778440, 0x6d8140, 0x6d8140, 0xc000128ad8, 0x16, 0x6d8140, 0xc000128ae0, 0x16)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:513 +0x526
github.com/google/go-cmp/cmp.(*state).compareAny(0xc0002be900, 0x775280, 0xc0000129c0)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:258 +0x18e6
github.com/google/go-cmp/cmp.Equal(0x6d8140, 0xc000128ad8, 0x6d8140, 0xc000128ae0, 0xc00000f580, 0x2, 0x2, 0x580c98)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:107 +0x406
github.com/google/go-cmp/cmp.Diff(0x6d8140, 0xc000128ad8, 0x6d8140, 0xc000128ae0, 0xc00012ab70, 0x1, 0x1, 0xc000106000, 0xc000106070)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare.go:127 +0x1ce
github.com/google/go-cmp/cmp_test.TestDiff.func1.1(0xc000241eb8, 0xc00023c600, 0xc0002f7ec8)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare_test.go:74 +0x138
github.com/google/go-cmp/cmp_test.TestDiff.func1(0xc000238d00)
        /home/bradfitz/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/compare_test.go:75 +0x99
testing.tRunner(0xc000238d00, 0xc0001c1bd0)
        /home/bradfitz/go/src/testing/testing.go:916 +0x19a
created by testing.(*T).Run
        /home/bradfitz/go/src/testing/testing.go:967 +0x652
FAIL    github.com/google/go-cmp/cmp    0.116s
```

**Comment by dsnet** [comment]
The logic for this is here: https://github.com/google/go-cmp/blob/b1c9c4891a6525d98001fea424c8926c6d77bb56/cmp/export_unsafe.go#L22

The ability to compare unexported fields is critical to many tests. Matt, you got any ideas for how to more safely retrieve an unexported field?

**Comment by mdempsky** [comment]
You have to convert UnsafeAddr to unsafe.Pointer before converting back to uintptr for pointer arithmetic.

I admit that's annoying, but it's what the unsafe rules strictly require (at least my reading of it).

**Comment by dsnet** [comment]
IIUC, you are suggesting this?
```go
return reflect.NewAt(f.Type, unsafe.Pointer(uintptr(unsafe.Pointer(v.UnsafeAddr()))+f.Offset)).Elem() 
```

**Comment by bradfitz** [comment]
@dsnet, try it and see? Does that make checkptr happy?

**Comment by mdempsky** [comment]
@dsnet Yeah, that should work.

**Comment by mdempsky** [comment]
I find the situation funny, and I'm glad others share my compiler nerd sense of humor. :)

I thought I'd elaborate a bit though to make sure folks understand this isn't a strictly theoretical/pedantic issue.

When compiling an expression with multiple function calls like `f() + g()`, we need to save `f()`'s return value on the stack while evaluating `g()`. We normally save it as the same type as what `f()` returns.

In the case of an expression like `unsafe.Pointer(v.UnsafeAddr() + g())`, we would save `v.Unsafe.Addr()`'s return value on the stack as a `uintptr` variable. So if `g()` triggers the garbage collector, the runtime will scan the stack; but because the address is saved as a `uintptr`, it will be skipped over. If this is the only remaining live reference to the variable, it could be garbage collected prematurely.

The compiler [specially recognizes](https://github.com/golang/go/blob/680ed10c9127a28ed9510c40d59b1ff10e688bff/src/cmd/compile/internal/gc/order.go#L1053) calls of the form `unsafe.Pointer(f())` (where `f()` has type `uintptr` and is immediately converted to `unsafe.Pointer`), and it saves them as an `unsafe.Pointer` variable instead. That guarantees expressions like `unsafe.Pointer(uintptr(unsafe.Pointer(v.UnsafeAddr())) + g())` are safe regardless of what `g()` does.

In go-cmp's code above, `g()` is actually just `f.Offset`, where this is a simple field access of a local variable. I can't off-hand think of any ways this code today could trigger the garbage collector, but in general, that's a bit iffy to rely on. E.g., if `f` was a pointer (so `f.Offset` is shorthand for `(*f).Offset`), the pointer dereference would involve instrumented calls into the runtime for `-race` and `-msan` modes; and for fuzzing, we're adding other forms of instrumentation around certain expression evaluations, which in general can also require runtime calls.

(Hopefully this was worthwhile to write up and share.)

**Comment by dsnet** [comment]
Personally, I think the oddity is more so due to the `reflect` package lacking type safety. I feel like golang/go#24654 or golang/go#26070 would have helped the situation.

Had the `reflect` package natively returned an `unsafe.Pointer`, the first cast from a `uintptr` to an `unsafe.Pointer` would not have been necessary.

**Comment by mdempsky** [comment]
@dsnet Yeah, I think the design of "safe" mode has had unfortunate long-term consequences for packages reflect and unsafe.
