### ISSUE TITLE
Could you please add html reporter?

### ISSUE THREAD

**Issue by grundic** [google/go-cmp#230]
Hi,

I would like to generate html output for my diffs in order to share with others. I wish it could have color and some interaction as well (like gerrit/github diff tool).
Could you please consider implementing this feature?

Thank you!

**Comment by dsnet** [comment]
It's difficult providing a HTML diff that satisfies every use case. Do we output it using `div`s or `span`s or some other HTML element? Do was using inlined styles or do we assume the presence of certain classes that correlate with certain colors? I think something like this is best left handled by other tools. While the `Diff` output is unstable, it does at least guarantee that removed lines are preceded by a `-` sign, and inserted lines are preceded by a `+` sign.

One possible HTML diff implementation could be:
```go
func HTMLDiff(x, y interface{}, opts ...cmp.Option) string {
	escapeSpan := func(color, body string) string {
		return `<span style="font-family:monospace; white-space:pre;` + color + `">` + html.EscapeString(body) + `</span><br>`
	}
	diff := cmp.Diff(x, y, opts...)
	if diff == "" {
		return ""
	}
	ss := strings.Split(diff, "\n")
	for i, s := range ss {
		switch {
		case strings.HasPrefix(s, "-"):
			ss[i] = escapeSpan(" color:red;", s)
		case strings.HasPrefix(s, "+"):
			ss[i] = escapeSpan(" color:green;", s)
		default:
			ss[i] = escapeSpan("", s)
		}
	}
	return strings.Join(ss, "\n")
}
```
This implementation emits `span`s with inlined styles.

Similarly, if you wanted a colorized output suitable for [terminals that support ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code):
```go
func ANSIDiff(x, y interface{}, opts ...cmp.Option) string {
	escapeCode := func(code int) string {
		return fmt.Sprintf("\x1b[%dm", code)
	}
	diff := cmp.Diff(x, y, opts...)
	if diff == "" {
		return ""
	}
	ss := strings.Split(diff, "\n")
	for i, s := range ss {
		switch {
		case strings.HasPrefix(s, "-"):
			ss[i] = escapeCode(31) + s + escapeCode(0)
		case strings.HasPrefix(s, "+"):
			ss[i] = escapeCode(32) + s + escapeCode(0)
		}
	}
	return strings.Join(ss, "\n")
}
```

**Comment by grundic** [comment]
Thank you very much for detailed answer (with examples 👍)

I agree, this is a good point: the diff library probably should not take care about the output, plus everyone could have different requirements.
On the other hand, the string output is not very flexible.

For example, [`godebug`](https://github.com/kylelemons/godebug/blob/master/diff/diff.go) provides a `Chunk` structure, which is a bit easier to work with.
Any chances the `go-cmp` could provide higher level abstractions like that, so that users can have more freedom?

**Comment by dsnet** [comment]
Throughout `cmp`'s history, it has made a number of significant changes to the exact output of `Diff`. The reason why it doesn't return a stable output is to hide details that are implementation specific. In its earlier history, each change to the output would unfortunately break a non-trivial number of users that had assumed that the output of `Diff` was stable for all time. This project prioritizes having the freedom to continually improve `Diff`'s output, and locking down its output (while a useful property in some contexts) unfortunately goes against that goal. For that reason, we have made the output unstable so that users can't accidentally rely on it as such.

For a similar reason, we also don't directly provide something similar to `godebug.Chunk` since that data structure fundamentally depends on the exact algorithm using for diffing. The current implementation used in `cmp` is guaranteed to be `O(n)`, but produces sub-optimal diffs in certain cases. We would like to improve the diffing algorithm to produce optimal output in more cases, but doing so may break users of a `Chunk`-like feature.

The closest equivalent of `Chunk` is [the `Reporter` feature](https://pkg.go.dev/github.com/google/go-cmp/cmp?tab=doc#Reporter). Even there, we document that "within a slice, the exact set of inserted, removed, or modified elements is unspecified and may change in future implementations."

**Comment by grundic** [comment]
I see.. Well, in this case I'd be happy to close the issue.
Still, your examples were a good starting point, appreciate your help!

Thank you 🤝

**Comment by VojtechVitek** [comment]
I find the colored output from the `ANSIDiff()` [example](https://github.com/google/go-cmp/issues/230#issuecomment-665750648) very useful. Thank you. 🎉 

I wish it was exposed as a function by the cmp package.
