### ISSUE TITLE
Allow specifiying global default options?

### ISSUE THREAD

**Issue by glenjamin** [google/go-cmp#241]
We use `go-cmp` heavily via `gotest.tools/assert.DeepEqual`.

After upgrading to the most recent version of protobuf, we are finding all of our comparisons are failing due to some new unexported fields. 

There is a  `cmp.Option` implementation provided by the protobuf module in https://godoc.org/google.golang.org/protobuf/testing/protocmp#Transform - but I now need to go and add this option to every single compare.

This particular check is generic and safe to add on every compare - would it be reasonable to provide a way to install such global comparison options?

**Comment by dsnet** [comment]
Global `cmp` options would go against the goal that each test's logic be side-effect free for another package's tests. Global options can be functionally achieved by creating an internal wrapper package over `cmp` that injects the relevant set of options that the module finds itself needing, and importing that wrapper package instead.

I should note that use of `reflect.DeepEqual` has always been flaky when used on protobuf messages, even prior to `v1.4.x`. It's just that `v1.4.x` made it more flaky. The correct way to compare a protobuf message is to use `cmp.Comparer(proto.Equal)` or `protocmp.Transform`.

In general, use of `reflect.DeepEqual` is dangerous on types that are not authored by the same team that is writing the test since it blindly compares unexported fields without any understanding whether the field may contain ephemeral data (e.g., caches, timestamps, locks, etc).

**Comment by glenjamin** [comment]
Thanks for the quick response, tha makes sense to me.

Do you have any thoughts on how the protobuf library could make this interop smoother?
