### ISSUE TITLE
Improve optimality of diffing algorithm

### ISSUE THREAD

**Issue by Eun** [google/go-cmp#244]
Given following example:
```golang
func TestDiff(t *testing.T) {
	fmt.Println(cmp.Diff(
		// Hello Universe
		[]uint8{0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65},
		// Hello World
		[]uint8{0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x57, 0x6f, 0x72, 0x6c, 0x64},
	))
}
``` 
sometimes reports
```
  []uint8{
  	... // 4 identical elements
  	0x6f,
  	0x20,
- 	0x55,
+ 	0x57,
- 	0x6e,
+ 	0x6f,
- 	0x69,
- 	0x76,
- 	0x65,
  	0x72,
- 	0x73,
+ 	0x6c,
- 	0x65,
+ 	0x64,
  }
```
sometimes
```
  bytes.Join({
  	"Hello ",
- 	"Universe",
+ 	"World",
  }, "")
```

_Originally posted by @Eun in https://github.com/google/go-cmp/issues/238#issuecomment-731204953_

**Comment by dsnet** [comment]
Implementation note: the current diffing algorithm is guaranteed to run in O(n) based on a  greedy search algorithm. There are other diffing algorithms that produce diffs that are guaranteed to be optimal (i.e., have the [shortest Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance)), but run in O(n^2). We should consider improving the diffing algorithm to have some degree of back-tracking so that it doesn't get stuck in a sub-optimal solution. At the same time, it's an important goal that the diffing algorithm avoid O(n^2) behavior.

**Comment by dsnet** [comment]
This appears to have been fixed by https://github.com/google/go-cmp/commit/449e17c6c9daf9b0c84a35fef7d79321b9535763
