### ISSUE TITLE
Feature Request: Remove the random diff output behavior

### ISSUE THREAD

**Issue by leighmcculloch** [google/go-cmp#250]
Diffs generated by go-cmp are random changed to prevent importers from relying on the output of the diffs. This logic lives here:
https://github.com/google/go-cmp/blob/ec71d6d790538ad88c95a192fd059e11afb45b6f/cmp/report_text.go#L25-L51

This idea of randomly generating output to prevent independence is interesting but it has side-effects for importers:
- An importer that uses the diff, isn't dependent on its output, but has tests, can't write tests that include the output.
- It's not intuitive and a developer can easily spend a lot of time trying to figure out why their diff output is changing for consistent data.

I'd like to propose, because of those ☝🏻  pain points, that go-cmp return a deterministic output all the time, even if it doesn't guarantee the format will stay consistent in future versions.

**Comment by dsnet** [comment]
> An importer that uses the diff, isn't dependent on its output, but has tests, can't write tests that include the output.

This is intentional, not a side effect. As such the [documentation](https://pkg.go.dev/github.com/google/go-cmp/cmp#Diff) instructs users to "not depend on this output being stable."

The output is deliberately random so that we have the freedom to change the reporter output. In the earlier days of `cmp`, the output could not be improved precisely because it would break the use-cases that assumed it would never change. It took effort to clean up all those cases and I believe it's a mistake to go back to that world where we cannot make improvements. The reporter output has regularly been improved in the past year or two and its ability to do so is thanks to the randomized output.

We understand the benefits of a stable output, but fundamentally such a goal goes against the freedom to make improvements. For this specific project, we consider freedom to change the output a greater benefit than stable output.

**Comment by leighmcculloch** [comment]
I understand the desire to prevent applications from depending on the output for functionality, but it is very difficult to use dependencies like go-cmp that cannot be tested. Thanks for explaining further.
