### ISSUE TITLE
reporter example does not work

### ISSUE THREAD

**Issue by yvonne2021** [google/go-cmp#267]
Hi there,
It seems the reporter example does not work. If you run the example code, it will raise the syntax error. It cannot recognize the function  MakeGatewayInfo which is defined in another file withing the same package.
https://pkg.go.dev/github.com/google/go-cmp/cmp@v0.5.6#example-Reporter

Thanks,
Yvonne

**Comment by dsnet** [comment]
\cc @jba. This is a valid `Example` according to `go test`, so I'm inclined to suspect that this is a bug with the `pkg.go.dev`.

**Comment by yvonne2021** [comment]
Thanks @dsnet for the quick response. I am very curious about this one. Do you think is it a bug in godoc or something can be improved in the reporter example code?

**Comment by yvonne2021** [comment]
![image](https://user-images.githubusercontent.com/84299809/126717872-94e139df-88c7-4d7a-9d28-2538b3955249.png)

**Comment by dsnet** [comment]
> Do you think is it a bug in godoc or something can be improved in the reporter example code?

If an example is valid according to `go test`, I'm inclined to say that `go.pkg.dev` should accept that as a valid test as well. Thus, I argue that it's a bug there. I doubt `cmp` is the only module with examples that fail to run due to a similar situation. Fixing it in `go.pkg.dev` fixes it for all those cases.

That said, the reporter example could probably circumvent the issue here by merging `example_reporter_test.go` into `example_test.go`.

**Comment by yvonne2021** [comment]
I see. It makes sense. I was thinking to fix it last night and thought it might be fixed to merge this into same file with function MakeGatewayInfo(). But it does not seem to be a very good solution as the function is in the same package as this example test file, as you said go test passed actually.
Sorry I am not that farmilar with go.pkg.dev. I guess maybe it is a limitation there to extract the dependencies from the same package and put it in to the example code in documentation.

**Comment by dsnet** [comment]
Closing as this is a problem with `pkg.go.dev` and not this module. There is nothing actionable here.
