### ISSUE TITLE
question: can this example be done more cleanly?

### ISSUE THREAD

**Issue by jba** [google/go-cmp#52]
In the data structure I wanted to compare, there was a field of type `I`, where `I` is an interface. Types `A` and `B` both implemented `I` and nothing else did. I wanted to convert `A`s to `B`s to facilitate comparison. (`A` is a deprecated version of `B`, and I wanted to treat them equivalently for comparisons.)

My first thought was a transformer from `A` to `B`. This failed, because `cmp.Equal` first checks that its two arguments have identical type before transforming. 

I ended up writing a comparer `func(x, y I) bool` that had to convert each of `x` and `y` before comparing them. ([Original code](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/query_test.go#L320)).

Is there a better way?

**Comment by dsnet** [comment]
`func (I, I) bool` seems to be the best approach, since you can't have a transformer occur on just one of the elements and not the other. The rationale for that was to ensure the path to each element was identical for both sides being compared. Otherwise, it would be very confusing how to print differences to the user.
