### ISSUE TITLE
What's the deal with trying the Equal() method"

### ISSUE THREAD

**Issue by filmil** [google/go-cmp#61]
It seems that go-cmp panics when encountering a nil struct that has an Equal method which doesn't handle nil values.

Here's a pull request that demonstrates the problem. #62

I think this is because there's no contract on what Equal method should do in the edge cases.  Indeed,, what should Equal do?

**Comment by dsnet** [comment]
Go has no operator overloading for `==`, so the `Equal` method has become the typical way that many objects declare how to compare themselves. This pattern occurs in the standard library, and an analysis of other Go code indicated that this was a common enough pattern to special case:
```
crypto/x509/x509.go:752:func (c *Certificate) Equal(other *Certificate) bool {
regexp/syntax/regexp.go:62:func (x *Regexp) Equal(y *Regexp) bool {
encoding/asn1/asn1.go:224:func (oi ObjectIdentifier) Equal(other ObjectIdentifier) bool {
time/time.go:252:func (t Time) Equal(u Time) bool {
net/ip.go:375:func (ip IP) Equal(x IP) bool {
```

**Comment by filmil** [comment]
I understand.

The reason I reported this was because of https://github.com/kubernetes/apimachinery/commit/44878ce55b93db86c07d1150129b626bf2ed0bd4#diff-221c91463b9db024401e40d997ec741c

Turns out, I was looking at an old version of K8S source that had a problem here. 

It would be nice, however, if go-cmp had some place that documented what requirements there are on Equal().

**Comment by dsnet** [comment]
The current paragraph that describes usage of the `Equal` method currently says:
> * If the values have an Equal method of the form "(T) Equal(T) bool" or "(T) Equal(I) bool" where T is assignable to I, then use the result of x.Equal(y). Otherwise, no such method exists and evaluation proceeds to the next rule.

If it helps, I can add a phrase to suggest this edge case:
> * If the values have an Equal method of the form "(T) Equal(T) bool" or "(T) Equal(I) bool" where T is assignable to I, then use the result of x.Equal(y) **even if x or y are nil pointers**. Otherwise, no such method exists and evaluation proceeds to the next rule.

Would that help?

**Comment by filmil** [comment]
... especially because it is all too easy to depend on code that makes this
mistake, and then you are fishing for reasons why it crashes.

**Comment by dsnet** [comment]
#63

**Comment by dsnet** [comment]
For future reference: I don't think we would ever change the semantics of when the `Equal` method is called since it useful for certain types to declare that the nil pointer to equal to the zero value of an allocated struct.

However, if this continues to bite people, we could consider recovering from a nil panic in `Equal` and performing the equivalent of `if (x == nil || x == nil) { return x == nil && y == nil }` on their behalf. However, this will slow down `cmp.Equal` further and is a hack I do not want to perform unless there is evidence of this being a pervasive problem.

**Comment by empijei** [comment]
Hi, sorry to necrobump, but I'd rather not open a duplicate issue.

Just wanted to point out that this problem bit someone today: https://github.com/golang/go/issues/28743

This is probably due to the fact that the `(T).Equal(T)` method is not really defined, declared or guaranteed to behave like `==` but people expect it to, and this package does too.

**Comment by m1kola** [comment]
I had this issue with `x509.Certificate` recently. I guess a workaround while we are waiting for https://github.com/golang/go/issues/28743 is to use a custom [`cmp.Comparer`](https://godoc.org/github.com/google/go-cmp/cmp#Comparer). Something like this:

```go
certCmp := cmp.Comparer(func(x, y *x509.Certificate) bool {
	if x == nil || y == nil {
		return x == y
	}

	return x.Equal(y)
})

cmp.Diff(something, other, certCmp) // or cmp.Equal
```
